### ISSUE TITLE
Database Maintenance

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/upptime#133]
We upgraded our backend databases during our normal maintenance window. We communicated this to enterprise customers but apologize for the impact to others. In the future maintenance windows will be announced here, so they'll appear on [our status website](https://upptime.ironcorelabs.com), and if watching this repository you'll be notified. We'll also announce maintenence via our Discord and GitHub community.

**Comment by BobWall23** [comment]
DB upgrade for identity database started at 20:11 GMT on Sunday, Dec. 1. DB upgrade for configbroker database started at 20:22 GMT. Identity DB upgrade finished at 20:29 PM, started upgrading replica. Configbroker DB upgrade finished at 20:39 GMT. Started upgrading replica. Identity replica upgraded 20:46.  CB replica completed. Identity service still failing health checks - completed analyze 21:07. Systems back up and functional.
