### ISSUE TITLE
🛑 Cloaked Search demo is down

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/upptime#62]
In [`71c03ec`](https://github.com/IronCoreLabs/upptime/commit/71c03ec9e8d0fbae25d97f2a413fad0fd04749f2
), Cloaked Search demo (https://cloaked-search.ironcorelabs.com/_cloaked_search/live) was **down**:
- HTTP code: 503
- Response time: 428 ms

**Comment by giarc3** [comment]
Service was back up on following refresh
