### ISSUE TITLE
🛑 Cloaked Search demo (backend search service) is down

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/upptime#63]
In [`a4a22aa`](https://github.com/IronCoreLabs/upptime/commit/a4a22aafd60ba6f7bd0bd0393157c82f90c20dae
), Cloaked Search demo (backend search service) (https://search-service.ironcorelabs.com/wikipedia_v2/_search?size=0) was **down**:
- HTTP code: 503
- Response time: 831 ms

**Comment by giarc3** [comment]
Service was back up on following refresh
